language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="desktop-file-utils libclutter-gtk-1.0-dev libgdk-pixbuf2.0-dev libgranite-dev libgtk-3-dev liblightdm-gobject-1-dev libwingpanel-2.0-dev libx11-dev meson libmutter-2-dev libgnome-desktop-3-dev valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build && ninja -C build test"

script:
 - echo BUILDS PASSED
